name: Create Release and Upload APK

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release and Upload APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.5

    - name: Flutter Clean
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --split-per-abi

    - name: Get Project Name
      id: get_project_name
      run: echo "::set-output name=name::$(awk '/name:/ {print $2}' pubspec.yaml | sed 's/ //g')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.get_project_name.outputs.name }} ${{ github.ref }}
        body: |
          Changes in this release:
          - Add APK for Android.

    - name: Upload APK to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/apk/release/*
        asset_name: app-release-${{ github.sha }}.apk
        asset_content_type: application/vnd.android.package-archive